completed week2 nodeJs assignment
shreyansh-khatri/NodeJs-Assignments pull request #2
Opened 2024-04-12 04:58 UTC by shreyansh-khatri

Pull Request Questionnaire

1) Briefly describe your change.
Completed NodeJs week2 assignments.

2) What parts of the application are affected by your change?
My changes only affected the week2 branch of this repository.

3) How did you test your change?
I tested various parts such as validation, different inputs and some other edge cases.

2024-04-15 06:36 UTC, RitikaGarg-ITT approved these changes

2024-04-15 07:01 UTC, choudhary-keshav requested changes

2024-04-15 07:01 UTC, choudhary-keshav commented on tsconfig.json
> +}
remove this commented code from tsconfig file!

2024-04-15 08:12 UTC, aditya-s-19 approved these changes

2024-04-15 08:23 UTC, choudhary-keshav approved these changes

2024-04-15 08:52 UTC, shreegovinda approved these changes

2024-04-16 04:04 UTC, anusreesubash approved these changes

2024-04-16 05:23 UTC, Harrrrry approved these changes

2024-04-16 05:29 UTC, merged